### ISSUE TITLE
unknown action: preview('/usr/local/bin/sysz' _fzf_cat {})

### ISSUE THREAD

**Issue by cassepipe** [joehillen/sysz#1]
I ran :
```
git clone https://github.com/joehillen/sysz.git
cd sysz
sudo make install # /usr/local/bin/sysz
```
and then `sysz` and I get `unknown action: preview('/usr/local/bin/sysz' _fzf_cat {})`

I am running `Linux Mint 20.2 x86_64`

**Comment by cassepipe** [comment]
The fix is simply to get install the newest version of `fzf` as the one from the package manager is a bit old (version 20)

**Comment by andynu** [comment]
Upgrading to the latest fzf didn't fix it for me.
```
% fzf --version
0.21.1 (334a4fa)
% sysz --version
 1.2.2
% sysz
unknown action: preview('/usr/local/bin/sysz' _fzf_cat {})
```

**Comment by joehillen** [comment]
Latest is [0.27.2](https://github.com/junegunn/fzf/releases/tag/0.27.2)
