### ISSUE TITLE
fzf version

### ISSUE THREAD

**Issue by savchenko** [joehillen/sysz#13]
Was there a specific reason for https://github.com/joehillen/sysz/commit/a31f0a8418b748f37a160bc3c43fec123997f56d?
Debian currently ships v0.24.3 in Stable which makes `sysz` incompatible without a manually-built `fzf`.

```sh
$ rmadison fzf
fzf        | 0.24.3-1+b6   | stable     | amd64
fzf        | 0.24.3-1+b6   | testing    | amd64
fzf        | 0.24.3-1+b6   | unstable   | amd64
```

**Comment by joehillen** [comment]
I use Arch. I don't like how Debian keeps around "stable" versions (a.k.a old and broken). The script could be made to work with older versions, but it would mean removing features when the script detects that version. Feel free to open a PR for that.

**Comment by joehillen** [comment]
Also 0.24.3 is almost a year old. What are they waiting for? https://github.com/junegunn/fzf/releases/tag/0.24.3

**Comment by joehillen** [comment]
FYI, fzf is a Go application, and its releases are a single binary, so you don't need to recompile to add it to your system. Just download the binary and add it to `/usr/local/bin/` and add `/usr/local/bin/` to your PATH if it isn't already.

```
~$ tar tf Downloads/fzf-0.27.2-linux_amd64.tar.gz
fzf
```

I'll add this to the manual install instructions.
