### ISSUE TITLE
v1.4.3 wget install issue

### ISSUE THREAD

**Issue by aklsh** [joehillen/sysz#16]
I tried using wget to install `sysz` but the URL given in the README gives a 404 as the sysz binary isn't released as an asset in v1.4.3.

```terminal
λ wget -O ~/.local/bin/sysz https://github.com/joehillen/sysz/releases/latest/download/sysz
--2021-11-13 22:54:44--  https://github.com/joehillen/sysz/releases/latest/download/sysz
Resolving github.com (github.com)... 13.234.210.38
Connecting to github.com (github.com)|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/joehillen/sysz/releases/download/1.4.3/sysz [following]
--2021-11-13 22:54:45--  https://github.com/joehillen/sysz/releases/download/1.4.3/sysz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2021-11-13 22:54:45 ERROR 404: Not Found.

```

Can the binary be added as an asset to the release?

**Comment by D-Maurel** [comment]
Same comment using `bin`, it seems that the 1.4.3 binary is missing.
You can still use `bin` with the following command:
```bash
bin install https://github.com/joehillen/sysz/releases/tag/1.4.1
```

**Comment by huned** [comment]
ping @joehillen - just ran into this bug as well. I decided to use 1.4.1 in the mean time. Thanks for the rad program :)

**Comment by joehillen** [comment]
Fixed. FYI, there is nothing special about the file in the github release page. It's the exact same file as this: https://raw.githubusercontent.com/joehillen/sysz/master/sysz

**Comment by huned** [comment]
tight @joehillen ⚡
