### ISSUE TITLE
Journal not working for user service

### ISSUE THREAD

**Issue by Croissong** [joehillen/sysz#18]
### Issue
Trying to open the journal for a user service, in this case `emacs.service`, does not show any entries. 

### Example:
```sh
sysz -V
# select emacs -> journal
> journalctl -xe --unit=emacs.service
```

In comparison, `journalctl --user -xe --unit=emacs.service` shows logs.

The same issue is present for other user services.

In the code you mentioned
>  \# remove --user flag from journalctl
    \# --user and --system don't work the same on journalctl
    
I don't fully understand the actual use cases for the corresponding journactl flags, but i suppose using them 1:1 is incorrect.
What also appears to work though is `--user-unit`:
```sh
journalctl -xe --user-unit=emacs.service
```
Maybe that's the proper way to select user services?

If you agree with this solution, I can attempt to create a PR for the changes :)

**Comment by joehillen** [comment]
> If you agree with this solution, I can attempt to create a PR for the changes :)

Please do. I noticed this a while ago and have been too busy to fix it.

**Comment by joehillen** [comment]
Also, since you'd be the first to open a PR, please feel free to make suggestions for any general improvements to the script.

**Comment by Croissong** [comment]
> please feel free to make suggestions for any general improvements 

I created #20 to help with consistent formatting & linting.

Another change i would like to make after getting familiar with the code: 
I want to make `sudo` opt-out (via flag), because on my system, systemd uses Polkit for authorization and therefore does not require sudo (i use arch btw).
Other users might have other setups which do not require sudo for most systemd unit actions, so i think a flag to never use sudo (and skip the `$EUID` check) makes sense. 
(I will open a separate PR soon)

**Comment by Croissong** [comment]
Added a few more minor changes for things i stumbled across.
Please have a look if they work for you as well :)
And if you have any improvement suggestions (other flag names etc.) please let me know!

**Comment by kiil** [comment]
For sysz 1.4.3 the journal command seems to always just return -- No entries -- for user services, also when sysz is started with the --user flag.

Output seems to be only `journalctl -xe --unit=something` also for user services, giving the empty result.
