### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by Nomarian** [joehillen/sysz#3]
Sorry, I gave this a try and it failed to run with this message

```
unknown action: preview('/usr/local/bin/sysz' _fzf_cat {})
```

Not very useful, but I've never used fzf so. maybe a newer version is required

**Comment by ShonFrazier** [comment]
same message for me on Ubuntu 20.04 with fzf 0.20.0

**Comment by joehillen** [comment]
The preview action was added in version 0.22 over a year ago.

https://github.com/junegunn/fzf#upgrading-fzf
