### ISSUE TITLE
[Feat] A shortcut to show the contents of the corresponding file

### ISSUE THREAD

**Issue by huyz** [joehillen/sysz#30]
It would be great to have a keybinding that lets you `cat` the contents of the corresponding file.

I see the path of the file listed on the `Loaded:` line. So I imagine it's possible.

**Comment by greyHairChooseLife** [comment]
@huyz 

IMO, we got that already. Pressing `ctrl+v` will satisfy you.

It comes from [readme](https://www.youtube.com/watch?v=wVYG1mu8Lg8)

Well, it makes me crazy that it is not toggling, tho.

**Comment by huyz** [comment]
Oh yeah I missed that. Thanks!

Btw, your link to `readme` is broken

**Comment by huyz** [comment]
Yeah a toggle would be very nice!  I'm sure a PR would be quite easy, no?

**Comment by greyHairChooseLife** [comment]
> Yeah a toggle would be very nice! I'm sure a PR would be quite easy, no?

@huyz 
I made it #31. It was not that easy for a noob like me, tho. :D

Btw, It was my first PR out of my personal boundary. You gave me courage. Happy I had tried. 
Thanks bro.
