### ISSUE TITLE
option "-s" is to set state in help but set manager in code

### ISSUE THREAD

**Issue by setop** [joehillen/sysz#6]
`sysz -u -s active` does not list user's active units but all system"s unit whatever the state.

code

https://github.com/joehillen/sysz/blob/8f5fa637a5f90b0d66d62f7426d2f421d3ce8191/sysz#L228

versus help:

https://github.com/joehillen/sysz/blob/8f5fa637a5f90b0d66d62f7426d2f421d3ce8191/sysz#L29

**Comment by setop** [comment]
@joehillen, what was wrong with this issue ?

**Comment by joehillen** [comment]
I fixed it

**Comment by setop** [comment]
OK
That's a good reason to close it :)
